### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by genialkartik** [ayushisingla/Spotify-Clone#1]
I'm also working on a similar kinda of project using Spotify's API.
I'll love to collaborate if you're using ReactJS, NodeJS or any other similar techonology Stack.

Happy Coding!✨

**Comment by ayushisingla** [comment]
Hey! 
This project is using power of core web technologies i.e. HTML, CSS and JavaScript, without using any framework or library. If you are interested in MERN stack, I am having another repository for Instagram-Clone in MERN. Do collaborate there!
